service: twitch-chat-event-source

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-prune-plugin
  - serverless-plugin-log-retention
frameworkVersion: '3'

custom:
  prune:
    automatic: false
    number: 0
  #myStage: ${opt:stage, self:provider.stage}
  logRetentionInDays: 30 # used to set a global value for all functions

provider:
  name: aws
  runtime: nodejs18.x
  versionFunctions: false
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ecs:RunTask
        - ecs:StartTask
        - ecs:StopTask
        - ecs:DescribeTasks
        - ecs:ListTasks
        - ecs:DescribeTaskDefinition
        - ecs:DescribeServices
        - ecs:UpdateService
        - ecs:ListTaskDefinitions
        - iam:PassRole
        - dynamodb:Query
        - dynamodb:GetItem
      Resource: "*"
    - Effect: "Allow"
      Action: 
        - "ssm:GetParameters"
      Resource: "*"

functions:
  handleStreamStart:
    handler: twitch-event-source.handleStreamStart
    events:
      - eventBridge:
          pattern:
            source:
              - 'hoagie.twitch-eventsub'
            detail-type:
              - 'Event'
            detail:
              subscription:
                type:
                  - 'stream.online'
    environment:
      TABLENAME: HoagieTools-prod
      TWITCH_CLIENT_ID: ${file(secrets.yml):twitchClientId_prod}
      TWITCH_CLIENT_SECRET: ${file(secrets.yml):twitchClientSecret_prod}

  handleStreamStop:
    handler: twitch-event-source.handleStreamStop
    events:
      - eventBridge:
          pattern:
            source:
              - 'hoagie.twitch-eventsub'
            detail-type:
              - 'Event'
            detail:
              subscription:
                type:
                  - 'stream.offline'
    environment:
      TABLENAME: HoagieTools-prod
      TWITCH_CLIENT_ID: ${file(secrets.yml):twitchClientId_prod}
      TWITCH_CLIENT_SECRET: ${file(secrets.yml):twitchClientSecret_prod}

  scheduledShutdown:
    handler: twitch-event-source.scheduledShutdown
    events:
      - schedule: cron(0 9 * * ? *)
          
    environment:
      TABLENAME: HoagieTools-prod
      TWITCH_CLIENT_ID: ${file(secrets.yml):twitchClientId_prod}
      TWITCH_CLIENT_SECRET: ${file(secrets.yml):twitchClientSecret_prod}